server:
  port: 8100
spring:
  application:
    name: news-server-web-admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 30Mb
dubbo:
  scan:
    base-packages: com.yzc.news.server.web.admin
  application:
    id: news-server-web-admin
    name: news-server-web-admin
  registry:
    id: zookeeper
    address: zookeeper://192.168.56.136:2181?backup=192.168.56.136:2182,192.168.56.136:2183