spring:
  application:
    name: news-server-service-admin
  datasource:
    druid:
      url: jdbc:mysql://192.168.56.136:3306/toutiao?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.yzc.news.server.domain
  mapper-locations: classpath:mapper/*.xml

dubbo:
  scan:
    base-packages: com.yzc.news.server.service.admin.api
  application:
    id: news-server-service-admin
    name: news-server-service-admin
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    address: zookeeper://192.168.56.136:2181?backup=192.168.56.136:2182,192.168.56.136:2183